### ISSUE TITLE
Icon not showing when adding to home screen on iOS

### ISSUE THREAD

**Issue by MarkWithall** [ThePacielloGroup/infusion#6]
Not sure if it's just me but the icon just shows as black when I go to the [infusion page](https://thepaciellogroup.github.io/infusion/) and select 'Add to Home Screen'.

![infusion-home-screen](https://user-images.githubusercontent.com/1871052/30579710-ab28f756-9d11-11e7-8e37-61d5eed01022.png)

It works when adding a bookmark.

![infusion-bookmark](https://user-images.githubusercontent.com/1871052/30579719-acebae26-9d11-11e7-9f8b-37e758b42ad9.png)

I'm using an iPhone 6s Plus with iOS 10.3.3. The use of `apple-touch-icon` in the code suggests it is intended to work.

**Comment by MarkWithall** [comment]
Some further investigate suggests that the icon needs to been in the root folder for it work (see [Apple developer documentation](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html). I've not had a chance to test this yet though.

**Comment by MarkWithall** [comment]
I didn't read far enough. The line after says that one can use icons in another folder.

As an reference example, https://html5boilerplate.com/mobile/ works as expected.

**Comment by Heydon** [comment]
@MarkWithall Thank you for the issue Mark. I'll investigate.

**Comment by Heydon** [comment]
@MarkWithall Is this with Safari?

**Comment by MarkWithall** [comment]
Yes. With Safari on iOS. Also, I've now updated to iOS 11.0.1 and the issue is still there.

**Comment by Heydon** [comment]
@MarkWithall Hi again, the issue appeared to be with Safari not accepting PNGs with transparency. I have replaced the images and the problem appears to be fixed.
![Infusion add to homescreen with correct icon](https://user-images.githubusercontent.com/683558/31007634-1538dbe0-a4f9-11e7-82c2-000d109a6aa3.png)
Can you confirm?

**Comment by MarkWithall** [comment]
Yes. Looks good to me. Thanks.

**Comment by Heydon** [comment]
@MarkWithall No problem. Hope you are getting on okay with Infusion besides this.

**Comment by wschlossberg** [comment]
Hi, I have added to iPhone home screen some frequently updated sites; as examples NOAA Northeast US Weather Satellite, Sports info from various.  They work fine but only display as icons on iPhone home screen as white blob—ugly.  I am not going to get NOAA, for example, to update their websites to include .png files.  Any way to select or use a better icon image for these?  I can provide an image/file and I don't expect it to update real time.  I just want something that looks nicer.  Latest iOS, etc.  Thank you.
