### ISSUE TITLE
Suggestion- add cursor:pointer to [for:themer]

### ISSUE THREAD

**Issue by extra808** [ThePacielloGroup/infusion#7]
https://github.com/ThePacielloGroup/infusion/blob/1be7bf70d5dc1ebe35c492aa373906c60ba5cd36/themes/infusion/static/css/styles.css#L202

The styling for the dark theme label could use the addition of cursor: pointer; to convey that it's clickable. 

Or make it an actual button (seems to require JavaScript to actually change the theme anyway) but that may have other ramifications I'm not clear on.

**Comment by Zegnat** [comment]
I tend to follow the recommendation of several design guides that [the hand cursor is for links](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b). The theme chooser does not navigate away from the current page, so it shouldn’t have anything other than the `default` cursor.

The real question then is if it is easy for people to identify it as a toggle button with the current design.

**Comment by extra808** [comment]
@Zegnat thanks, that makes sense. I was responding to my impression that it was just text, not a control. Part of it may be the very small border radius, not having a border that's visually distinct from the inner and outer background colors is also a factor. I think something about it being centered along with the rest of the text in the footer detracts from its button-ness. 

Being at the end of the content at all is not where I expect to find a control for altering the page I just read; moving it from the footer to the header could make it more clear.

**Comment by Heydon** [comment]
@Zegnat @extra808 I have made the border radius more obvious. Thanks for the heads-up! #1a70436f2809f344553b11a7bc8b5dea90d5a7ae
